### ISSUE TITLE
Link issue for Folks app source code

### ISSUE THREAD

**Issue by aaronj1335** [jpgiance/portfolio#2]
👋  Hi Jorge! Hope you're doing well! I got your message and was checking out the app (looks cool!), and I noticed that your portfolio's link to the code doesn't work for me. Maybe it's a private repo?

**Comment by jpgiance** [comment]
Hi! Thanks for checking. You should be able to see it now. I am trying to
validate the idea. If people like it, maybe launching a Kickstarter
